"""Assemble source-linked cards and original per-case learning sections."""
from pathlib import Path
import json
import nbformat
ROOT=Path(__file__).resolve().parents[1]
CAT=json.loads((ROOT/'data/industries/catalog.json').read_text())['datasets']
# Original teaching additions; source facts remain in cards and source notes.
NOTES={
'wdbc':('Stages 00–03 and 07–12','A medical-sounding name does not turn a teaching classifier into a medical device.',
'''For a hand calculation, consider a controlled confusion matrix with 90 benign and 10 malignant examples. A rule calling everything benign gets 90 correct, but malignant recall is zero. Balanced accuracy is (1 + 0)/2 = 0.5. This is an invented arithmetic control, not a result measured on this dataset. Compare it with the real confusion matrix produced by the notebook. Explicitly say which is which.

The original measured features describe variation among cell nuclei. Our standardized point cloud compares image summaries; we never reconstruct actual three-dimensional cells. Computing homology after projecting to two coordinates answers a question about that projection. It can merge or separate structures that differ in the original feature space. Test a controlled projection before interpreting a real plot.''',
['Explain why `label == 0` means positive malignancy in this loader but is not a universal label convention.','Draw a confusion matrix for an always-benign classifier and calculate both ordinary and balanced accuracy.','Identify the absent identifiers that prevent verifying a hospital-level or patient-level holdout.','Explain why a cohort persistence diagram is not one diagnosis per row.'],
['Read the explicit label map; our binary teaching target intentionally maps malignant to one.','Balanced accuracy averages the two recalls; ordinary accuracy weights classes by their sample counts.','The snapshot lacks original patient and site identifiers, so a random row split cannot establish either separation.','The filtration is constructed from many observations and a selected metric; no individual clinical mechanism follows from it.']),
'wine':('Stages 01–02 and 06–12','A good topological experiment must make a descriptor available for a genuinely new query.',
'''Use a hand-checkable geometry before the real chemistry: points at (0,0), (1,0), (1,1), (0,1). Under the edge-distance Rips convention, the perimeter loop is born at 1 and filled when diagonal edges and triangles enter at square-root two. The full small filtration—not a graph without triangles—is required. Multiply all coordinates by two and check the interval scales by two.

Now connect that test to the chemistry. The same idea applies in thirteen standardized coordinates; no two-dimensional picture is required for computation. Each local query complex contains the query and eight fixed-training neighbors. Changes in the reference cloud or standardization alter the question. Reserving reference rows keeps the supervised fitting query from including itself as a training landmark. It costs fitting data, so the raw-feature comparison uses that same reduced fitting set.''',
['Why is cultivar not an ordinal quality target?','Why are reference rows excluded from supervised fitting rows in this comparison?','Which six descriptor entries should change under uniform scale multiplication?','What new evidence is needed before saying topology improves wine analysis generally?'],
['The categories label origins/cultivars, not a numeric quality scale.','It avoids giving training queries a self-reference advantage absent for unseen queries; all models use the same supervised rows.','H0 mean/std/max and H1 maximum/total lifetime scale; the H1 count stays unchanged away from numerical tolerance issues.','Independent data and a locked selection procedure, with uncertainty and suitable baselines; one exposed split is insufficient.']),
'stackloss':('Stages 01–02, 10–12, 21 and 26–27','A small observational table is useful for learning model fragility, not certifying a reactor.',
'''Calculate an ordinary mean and one residual before running Ridge. If a source-scale observation is 20 and a prediction is 15, the signed residual observed minus predicted is 5; its absolute error is 5. Do not convert it to kilograms or a flow rate without a documented unit relationship. When a label uses an encoded percentage, keep the encoding explicit in plots.

The source row order is preserved for a simple train/validation/test demonstration. Missing timestamps prevent claiming a faithfully reconstructed future operating shift. The leave-one-training-row-out exercise asks how much individual observations influence a prediction. It does not increase the number of independent experiments. A large neural network might memorize these rows; that is not evidence of an identifiable physical state or safe control behavior.''',
['Why must the holdout be described as source-order rather than a verified operational-time split?','What changes when scaling is refit in each leave-one-out training fold?','Why can a PINN with a wrong boundary condition still produce low training error?','List four observations needed for an independently testable plant conservation model.'],
['No original timestamps are provided to validate the presumed order.','The omitted row no longer helps determine feature means/scales, so the experiment respects the held-out information boundary.','A numerical training fit is not proof that its imposed equations and boundary conditions describe the real plant.','Examples include calibrated flow rates, concentrations, temperature units, storage changes, timestamps and actuator/operating conditions.']),
'grunfeld':('Stages 00–03, 10–12, 19 and 21','Two records from the same company are not two independently sampled companies.',
'''Write two records for one imagined firm: year t has investment 100, year t+1 has investment 120. A last-investment baseline predicts 100 for the later record and incurs absolute error 20. That arithmetic says nothing about causality. A fitted coefficient using capital and value may capture association, firm scale or missing covariates.

Our panel shift happens within each firm. A shift on the entire concatenated table would accidentally use the last record of one company as the previous record for another. This is a silent data-engineering failure that can survive model training. Compare same-firm chronological evaluation with leaving entire firms out; the latter tests a different generalization question. Publication delays and later accounting revisions are not in this snapshot, so the availability assumption stays qualified.''',
['Why is a shift within firm necessary?','Why is same-year year-end value unavailable for a start-of-year forecast?','What does a known-firm future-year test not establish?','Does a capital coefficient identify the causal effect of buying equipment?'],
['It preserves entity continuity and avoids crossing from one company to the next.','Its measurement time is after the decision boundary; a lagged record is a simplified but clearer information set.','It does not establish performance on previously unseen firms or modern economic conditions.','No; selection, omitted causes and simultaneous decisions are not removed by ordinary predictive regression.']),
'co2':('Stages 00–03, 07–12 and 18–22','The time axis and the missingness mask are part of the dataset.',
'''Take a controlled weekly sequence [10,11,NaN,13,14,15]. Removing NaN makes 11 and 13 appear adjacent. A first-difference computed as if one week separates them is wrong. Keeping the calendar slots allows the window builder to reject unsupported examples rather than silently change their meaning. The notebook writes source indices so every forecast can be traced back to raw measurements.

A training-only local-shape transform subtracts a window's first value from each coordinate. It removes that window's level but retains short-term differences. It is an explicit representation choice, not a recovery of an invariant atmospheric state. A diagram that changes after detrending may be telling you about the preprocessing, not a discovered new physical phenomenon.''',
['Why does dropping missing rows distort a fixed weekly lag?','What is the target index for length three, end index two, horizon two?','How does observed-history one-step testing differ from free-running rollout?','Why is a seasonal-looking loop not proof of a reconstructed atmospheric attractor?'],
['Adjacent remaining rows may no longer be seven days apart.','Four; only positions zero through two are predictors.','Observed-history uses actual prior readings as they arrive; free running feeds predictions back and compounds errors.','The embedding, sampling, noise, forcing and mathematical recovery assumptions need independent justification.']),
'nile':('Stages 02, 07–12, 19 and 21','A detected change is a descriptive result until its cause is independently established.',
'''For a controlled signal of eight zeros followed by eight ones, the split before the first one yields two constant segments and zero within-segment squared error. The unit test checks that exact result. A real river series has nonzero noise and dependence. Searching many cut points makes the chosen one look better by construction; the winner is not itself a significance test.

The model uses annual total volume, not instantaneous water speed or discharge. To convert volume to average rate you would need an explicit duration and consistent units. Even then you would not know subannual peaks or extreme-event timing. Such missing resolution matters for operational infrastructure decisions; it cannot be repaired by using a more expressive neural architecture.''',
['Why is the two-mean search retrospective?','How does annual volume differ from instantaneous discharge?','Why must the change point be selected without reading the future evaluation years?','Which missing quantities prevent this one series from specifying a full hydrology PDE?'],
['It uses observations on both sides of candidate changes within the fitted period.','One is an integral amount over a year; the other is a rate at a time.','Otherwise future outcomes influence the fitted regime description and contaminate the declared prediction task.','Spatial boundaries, forcing, inflows/outflows, storage, calibrated parameters and subannual observations are examples.']),
'elnino':('Stages 01–03, 07–12, 21–22 and 28','A calendar baseline makes the representation and evaluation more interpretable.',
'''Suppose the mean January temperature in the chosen training years is 24 degrees C. A January observation of 25.5 has an anomaly of +1.5 degrees relative to that baseline. This controlled arithmetic does not assert that all published climate anomaly products use our baseline. In the notebook the twelve training monthly means are calculated and saved explicitly.

The monthly long view is derived by a fixed column order; alphabetically sorting month names would scramble chronology. After reshaping, the window constructor uses an integer month index. A temperature in one regional record is not a spatial field. Operator training needs varying input functions or conditions with corresponding solution functions, so the optional field-simulation path is separate from this observed scalar time-series exercise.''',
['Why must the reference period accompany an anomaly value?','Why is alphabetical month ordering wrong?','Can the same 732 values become independent PDE solutions just by creating windows?','Why must we compare last value and monthly climatology before more complicated models?'],
['Subtracting a different fitted baseline changes the anomaly without changing the original measurement.','Calendar order is a semantic property, not the alphabetic order of names.','No; overlapping transformations do not create independent simulation initial conditions or solution fields.','They encode strong simple persistence/seasonality structure; complexity alone is not evidence of useful prediction.']),
'modechoice':('Stages 00–03, 07–12 and 19','The physical or decision-making unit must survive reshaping and splitting.',
'''With 210 travelers and four alternatives each, the array has 840 alternative records. A person-level prediction requires selecting one of the four modes once for each traveler. A split after pivoting gives one independent choice set per row. A split before pivoting could put part of a person's choice set into the fitting data and another part into the test data.

Cheapest offered mode is a concrete baseline, not an assumption that price alone determines behavior. Waiting time, travel time, income and unobserved preferences can matter. Our classifier does not estimate an intervention effect from changing a ticket price. The source sampled choices disproportionately; a probability distribution in this sample is not a population market-share forecast.''',
['Why do 840 records not imply 840 independent decisions?','Why exclude `choice` and the potentially post-choice `psize` from features?','How can probabilities sum to one and still be uncalibrated for a population?','What is analogous to traveler grouping in sports and healthcare?'],
['Four alternatives describe the same decision made by each of 210 people.','The first is the target; the second is tied to the chosen mode and has questionable pre-decision availability.','Normalization is an algebraic property, not evidence that a selected sample represents the intended population.','Repeated shots from athletes, records from patients, and observations within sessions must be grouped according to the generalization claim.'])}

for meta in CAT:
    name=meta['id'];prereq,idea,worked,questions,answers=NOTES[name]
    card=f'''# Dataset card: {name}\n\n## Identity and evidence\n\n**Title:** {meta['title']}\n\n**Sector:** {meta['sector']}. **Kind:** observed historical data. **Canonical snapshot:** {meta['rows']} rows.\n\n**Source attribution:** [{meta['citation']}]({meta['source_url']})\n\n**Reuse basis:** [{meta['license']}]({meta['license_evidence_url']}). '''
    if name in ('wdbc','wine'):card+='The normalized snapshot is an adaptation of the distributed source. Attribution, source, license link and changes are recorded here; no endorsement is implied. '
    card+=f'''\n\n**Acquisition:** {meta['acquisition']}, using {meta['provider']} {meta['provider_version']}. Primary documentation reviewed 2026-09-20. The current online documentation may describe a newer package release; the files and hashes here identify the actual distribution used.\n\n**Observation unit:** {meta['observation_unit']}\n\n**Limitations:** {meta['scope_limitations']}\n\n## Files and provenance\n\n[Normalized CSV](../../{meta['data_file']}) · [Original package-distribution CSV](../../{meta['source_file']}) · [Machine-readable metadata](../../data/industries/{name}/metadata.json)\n\nNormalized SHA-256: `{meta['data_sha256']}`\n\nOriginal distribution SHA-256: `{meta['source_sha256']}`\n\nChanges: {' '.join(meta['transforms'])}\n\nMissing values by column: `{json.dumps({k:v for k,v in meta['missing_by_column'].items() if v})}`. An empty object means none are present, not that real-world measurement uncertainty is zero.\n\n## Complete column dictionary\n\n| Column | Role | Units / encoding | Meaning |\n|---|---|---|---|\n'''
    for s in meta['schema']:
        card+=f"| `{s['name']}` | {s['role']} | {s['units']} | {s['description']} |\n"
    if meta['label_map']:card+='\nExplicit loader label map: `'+json.dumps(meta['label_map'])+'`. These are not automatically the original provider codes.\n'
    card+=f'''\n## Evaluation and approved learning use\n\nRead the [case lesson](../lessons/{name}.md) before the [worked notebook](../notebooks/{name}.ipynb). The notebook persists its split, source identifiers, fitted transforms where applicable, predictions and metrics under `reports/v6/industries/{name}/`. Its test partition is already exposed in the reference outputs. New tuning requires a new protocol.\n\nThe data are suitable for the stated teaching calculation, not certified clinical decisions, trading, process control, dam operations, operational climate forecasting or transport interventions. Scale, age and missing metadata limit claims independently of prediction accuracy.\n\n## Rebuild without inventing records\n\nNormal lessons read the bundled CSV. To intentionally recreate the snapshots install the recorded distributions using the optional `data-rebuild` extra, then run `python scripts/prepare_industry_data.py --replace`. This explicitly overwrites snapshots and requires rerunning every verification. The raw distribution copy allows comparison before and after normalization. No web download is represented as having succeeded.\n'''
    (ROOT/f'industry/cards/{name}.md').write_text(card)
    nb=nbformat.read(ROOT/f'industry/notebooks/{name}.ipynb',as_version=4)
    walkthrough='\n\n'.join(c.source for c in nb.cells if c.cell_type=='markdown')[len(nb.cells[0].source):]
    lesson=f'''# {meta['title']}\n\n**Prerequisite route:** {prereq}. Beginners can inspect the data first and return to the advanced parts after the prerequisite stages.\n\n**Central idea:** {idea}\n\nStart with the [shared beginner data primer](../../docs/v6/BEGINNER_DATA_PRIMER.md), then the [dataset card](../cards/{name}.md). Open the [worked lab](../notebooks/{name}.ipynb) only after predicting its first result.\n\n## What you should be able to explain\n\nBy the end, identify the observation unit, separate a stored row from an independent example, justify the metric or representation, describe which data fit each transform, calculate the relevant baseline, and reject an unsupported domain claim. Software success and scientific interpretation are assessed separately.\n\n## Work a small example first\n\n{worked}\n\n## Walk through the real-data experiment\n{walkthrough}\n\n## Independent conceptual questions\n'''
    for i,q in enumerate(questions,1):lesson+=f'\n**{name}.Q{i}.** {q}\n'
    lesson+=f'''\n## Independent code and delayed recall\n\nUse [your learner notebook](../learner/{name}.ipynb), then compare with the [worked answers](../answers/{name}.ipynb). Do not use the answers as an input to your first attempt. After a delay, explain the observation unit, the main leakage trap, and a result this data cannot establish without reopening the lesson.\n\n## Mastery evidence\n\nSave `my_work/industries/{name}.md` with a prediction, a hand calculation, one changed-code experiment, observed output and one limitation. Record the dataset hash and exact source rows you evaluated. To pass, all three coding tasks must run, the four conceptual answers must be correct, and the central leakage/interpretation error must be corrected. An independent delayed explanation—not a checkmark—is the retention evidence.\n'''
    (ROOT/f'industry/lessons/{name}.md').write_text(lesson)
    ans=f'# Conceptual answer criteria: {name}\n\nAttempt the questions in the lesson first. These criteria do not automatically assess your work.\n'
    for i,(q,a) in enumerate(zip(questions,answers),1):ans+=f'\n## {name}.Q{i}\n\n{q}\n\n**Reasoning:** {a}\n'
    ans+='\n## Delayed recall\n\nState the observation unit; reconstruct the main information-leakage failure; give one unsupported claim and name the missing evidence. A response that only repeats the model name has not passed.\n'
    (ROOT/f'industry/answers/{name}.md').write_text(ans)
print('Created eight cards, lessons and answer-criteria files')
